# Generated by Django 4.0.1 on 2022-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_user_avatar_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
