version: "3.7"

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application
    volumes:
      - ./backend/:/backend/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    container_name: backend_ngnix
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - 8000:80
    depends_on:
      - backend

  minio_server:
    container_name: minio
    image: minio/minio:RELEASE.2021-03-26T00-00-41Z-35-g5cce9361b
    command: minio server /data
    ports:
      - 9000:9000
    volumes:
      - minio-storage:/data
    environment:
      - MINIO_HOST=localhost
      - MINIO_ALIAS=localhost
      - MINIO_BUCKET=test-bucket

volumes:
  postgres_data:
  minio-storage:
    name: minio-storage
