import { createSlice, PayloadAction, createAsyncThunk } from "@reduxjs/toolkit";
import { RootState } from "../../state/store";
import type { User } from "../../types/user";
import { getUserViaToken } from "../../services/api";
import { toast } from "react-toastify";

export interface AppState {
  user: User | null;
  isDrawerOpen: boolean;
}

const initialState: AppState = {
  user: null,
  isDrawerOpen: false,
};

export const setUserByToken = createAsyncThunk(
  "app/setUserByToken",
  async ({ token, refreshToken }: { token: string; refreshToken: string }) => {
    // The value we return becomes the `fulfilled` action payload
    const { id, email, first_name, last_name, phone_number } =
      await getUserViaToken();
    const user: User = {
      id,
      email,
      firstName: first_name,
      lastName: last_name,
      phoneNumber: phone_number,
      token,
      refreshToken,
    };
    return user;
  }
);

export const AppSlice = createSlice({
  name: "app",
  initialState,
  reducers: {
    setUser: (state, { payload: user }: PayloadAction<User>) => {
      state.user = user;
    },
    logout: (state) => {
      state.user = null;
    },
    toggleDrawer: (state) => {
      state.isDrawerOpen = !state.isDrawerOpen;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(setUserByToken.fulfilled, (state, action) => {
        state.user = action.payload;
      })
      .addCase(setUserByToken.rejected, (state) => {
        toast.error("Failed to fetch user data");
      });
  },
});

// ACTION CREATORS are generated for each case reducer function
export const { setUser, logout, toggleDrawer } = AppSlice.actions;

// Other code such as selectors can use the imported `RootState` type
// Object containing all selectors
export const select = {
  user: ({ app }: RootState) => app.user,
  isDrawerOpen: ({ app }: RootState) => app.isDrawerOpen,
};

export default AppSlice.reducer;
