# Generated by Django 4.0.1 on 2022-06-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='testFile', max_length=100),
            preserve_default=False,
        ),
    ]
